# Generated by Django 4.0.5 on 2022-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cupon_delete_price_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
