# Generated by Django 4.0.5 on 2022-06-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cupon_valid_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cupon',
            new_name='Coupon',
        ),
    ]
